FROM python:3.9-slim

WORKDIR /app

COPY ./endpoints.py .

RUN pip install --no-cache-dir fastapi==0.68.0 uvicorn[standard]==0.15.0 transformers datasets evaluate accelerate optimum[exporters,onnxruntime]

CMD ["uvicorn", "endpoints:app", "--host", "0.0.0.0", "--port", "8118"]