ARG CUDA_IMAGE="12.1.1-devel-ubuntu22.04"
FROM nvidia/cuda:${CUDA_IMAGE} AS build

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git build-essential python3.9 python3-pip gcc wget \
    ocl-icd-opencl-dev opencl-headers clinfo \
    libclblast-dev libopenblas-dev && \
    echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1 && \
    python3 -m pip install --no-cache-dir --upgrade pip

WORKDIR /app

RUN pip install --no-cache-dir fastapi==0.68.0 uvicorn[standard]==0.15.0 transformers datasets evaluate accelerate optimum[exporters,onnxruntime-gpu]

COPY ./endpoints.py .
